// import { Geist, Geist_Mono } from "next/font/google";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import FooterSection from "@/components/layout/Footer";
import WhatsappButton from "@/components/layout/whatsappbutton";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const openSans = Open_Sans({
  subsets:["latin"],
  variable: "--font-open-sans",
})

const poppins = Poppins({
  subsets:["latin"],
  weight:["300","400","500","600","700"],
  variable:"--font-poppins",

})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon:"/images/common/favicon.jpg"
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        {children}
        <WhatsappButton/>

        <FooterSection/>


        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-738880229"
          strategy="afterInteractive"
        />

        <Script id="google-ads" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-738880229');
          `}
        </Script>


      </body>
    </html>
  );
}
