import Image from "next/image";

export default function TypesOfDentalBracesSection() {
  const bracesTypes = [
    {
      image:
        "https://lightslategray-lemur-726893.hostingersite.com/cdn-imgs/dental-treatment-options-imgs/orthodontics.jpg",
      title: "Metal Braces",
      description:
        "The most common braces are made from high grade stainless steel. These are used for many different reasons such as straightening teeth, aligning your bite.",
        bgColor: "#0CC0CC",
    },
    {
      image:
        "https://lightslategray-lemur-726893.hostingersite.com/cdn-imgs/dental-braces-page-imgs/Clear-Braces.jpg",
      title: "Clear Ceramic Braces",
      description:
        "Ceramic braces are clear brackets that are designed to blend in with your teeth. These clear braces are made of a translucent (clear) material.",
        bgColor: "#A0D133",
    },
    {
      image:
        "https://lightslategray-lemur-726893.hostingersite.com/cdn-imgs/dental-braces-page-imgs/Invisalign.jpg",
      title: "Invisalign",
      description:
        "The Invisalign system is a series of custom made clear removable aligners, that are generated by computer simulation to gradually move the teeth.",
        bgColor: "#FFCC00",
    },
  ];

  return (
    <section className="py-10 bg-white">
      <div className="w-[70vw] mx-auto">
        
        {/* Sub Heading */}
        <h3 className="text-2xl md:text-2xl font-semibold text-[#36384F] mb-8">
          What are the types of dental braces?
        </h3>

        {/* Content */}
        <div className="text-[#36384F] text-lg leading-relaxed text-justify">

          <h4 className="font-semibold text-xl mb-3">
            Metal Braces
          </h4>

          <p className="mb-8 text-[15px]">
            The traditional ones that treat extreme overcrowding and abnormal
            alignment of teeth and jawline. The <strong>metal braces</strong>{" "}
            help align the teeth and jawline in small increments at a time.
            In modern times, metal braces come with a wide range of color
            options that make them more visually appealing.

            While they seem like an inconvenience and a lengthy method,
            once your treatment is done, your smile will be the reward
            you will get.
          </p>

          <h4 className="font-semibold text-xl mb-3">
            Clear Ceramic Braces
          </h4>

          <p className="mb-8 text-[15px]">
            <strong>Invisible braces</strong> /{" "}
            <strong>Ceramic braces</strong> /{" "}
            <strong>Clear braces</strong> and metal braces are almost the same;
            however, the only difference between them is that one is less
            visible than the other.

            <strong> Tooth-colored braces </strong>
            or clear ceramic braces are attached to the teeth surface just like
            metal braces and provide similar treatment results.
          </p>

          <h4 className="font-semibold text-xl mb-3">
            Invisalign
          </h4>

          <p className="mb-14 text-[15px]">
            To achieve a prettier smile, <strong>Invisalign</strong> treatment
            can be done. Invisalign treatment is a go-to choice for those with
            mild to severe malocclusions.

            Clear plastic aligner trays are used in this process to shift the
            teeth gradually into proper alignment. The patients are required
            to wear it for at least 20 hours a day.

            It can be removed very easily, allowing the patients to brush,
            floss, and maintain their oral health as they normally do.

            Invisalign is apt for those who are conscious about their appearance
            as it looks like a clear plastic mold and is completely invisible.

            There is no restriction in chewing hard foods with Invisalign
            treatment as is commonly with other braces treatment.
          </p>
        </div>

        {/* Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
  {bracesTypes.map((item, index) => (
    <div
      key={index}
      className="
        overflow-hidden
        transition-all
        duration-300
        hover:-translate-y-2
        flex
        flex-col
        h-full
      "
    >
      {/* Image */}
      <div
      className="h-[250px] flex items-end justify-center"
      >
      <Image
        src={item.image}
        alt={item.title}
        width={600}
        height={400}
        className="w-auto max-h-full object-contain"
      />
      </div>

      {/* Content */}
      <div
        className="
          flex
          flex-col
          flex-1
          justify-center
          items-center
          p-6
        "
        style={{ backgroundColor: item.bgColor }}
      >
        <h4 className="text-2xl font-semibold text-white text-center mb-4">
          {item.title}
        </h4>

        <p className="text-white text-center leading-relaxed">
          {item.description}
        </p>
      </div>
    </div>
  ))}
</div>

      </div>
    </section>
  );
}